
version: '3'

services:
  prompt-creator-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./config:/app/config
    environment:
      - PORT=80
      - NODE_ENV=production
    restart: unless-stopped
