
version: '3'

services:
  prompt-creator-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - config-data:/app/config
    environment:
      - PORT=80
    restart: unless-stopped

volumes:
  config-data:
